export const projects = [
  {
    id: 0,
    image: "/assets/projeto1.png",
    techs: "HTML and CSS",
    url: "https://amy-portfolio.vercel.app/",
    git: "https://github.com/MatheusCaires04/AMY-portfolio",
  },
  {
    id: 1,
    image: "/assets/projeto2.png",
    techs: "HTML, CSS and JS",
    url: "https://website-plants.vercel.app/",
    git: "https://github.com/MatheusCaires04/website-plants",
  },
  {
    id: 2,
    image: "/assets/projeto3.png",
    techs: "HTML and CSS",
    url: "https://disney-plus-clone-six-beta.vercel.app/",
    git: "https://github.com/MatheusCaires04/clone-page-initial-disneyplus",
  },
  {
    id: 3,
    image: "/assets/projeto4.png",
    techs: "HTML and CSS",
    url: "https://flexblog-alpha.vercel.app/",
    git: "https://github.com/MatheusCaires04/flexblog",
  },
  {
    id: 4,
    image: "/assets/projeto5.png",
    techs: "HTML, CSS, JS and API Pokémon",
    url: "https://yourpokemon.vercel.app/",
    git: "https://github.com/MatheusCaires04/pokeapi",
  },
  {
    id: 5,
    image: "/assets/projeto6.png",
    techs: "HTML, CSS, JS and API Wather",
    url: "https://weatherapi-xi.vercel.app/",
    git: "https://github.com/MatheusCaires04/weatherapi",
  },
  {
    id: 6,
    image: "/assets/projeto7.png",
    techs: "NextJS, TailwindCSS, Swiper Slide",
    url: "https://food-website-green-six.vercel.app/",
    git: "https://github.com/MatheusCaires04/portfolio",
  },
  {
    id: 7,
    image: "/assets/projeto8.PNG",
    techs: "VITE, TailwindCSS, Swiper Slide",
    url: "https://foodabbraccio-clone.vercel.app/",
    git: "https://github.com/MatheusCaires04/foodabbraccio",
  },
  {
    id: 8,
    image: "/assets/projeto9.PNG",
    techs: "VITE, TailwindCSS",
    url: "https://rentupconstruction-website.vercel.app/",
    git: "https://github.com/MatheusCaires04/rentupconstruction-website",
  },
  {
    id: 9,
    image: "/assets/projeto10.png",
    techs: "VITE, TailwindCSS",
    url: "https://mbstore.vercel.app/",
    git: "https://github.com/MatheusCaires04/mbstore",
  },
  {
    id: 10,
    image: "/assets/projeto11.png",
    techs: "VITE, TailwindCSS",
    url: "https://lofi-life-clone.vercel.app/",
    git: "https://github.com/MatheusCaires04/lofi.life-clone",
  },
  {
    id: 11,
    image: "/assets/projeto12.png",
    techs: "VITE, TailwindCSS",
    url: "https://disney-clone-tau-lemon.vercel.app/",
    git: "https://github.com/MatheusCaires04/disney-clone",
  },
];
